[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"


[project]
name = "npfactorial"
version = "0"
description = "Stupid Package that computes a factorial using numpy"
dependencies = ["numpy"]